name: Build Norminette AppImage

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download appimage-builder
      run: |
        wget -O appimage-builder-x86_64.AppImage https://github.com/AppImageCrafters/appimage-builder/releases/download/v1.1.0/appimage-builder-1.1.0-x86_64.AppImage
        chmod +x appimage-builder-x86_64.AppImage
    
    - name: Build AppImage
      run: ./appimage-builder-x86_64.AppImage --recipe AppImageBuilder.yml --skip-test
        
    - name: Upload AppImage to release
      uses: softprops/action-gh-release@v1
      with:
        files: "*.AppImage"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
