name: Build Norminette AppImage

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install appimage-builder
      run: |
        sudo apt update
        sudo apt install -y python3-pip python3-setuptools patchelf desktop-file-utils libgdk-pixbuf2.0-dev fakeroot strace
        pip install appimage-builder
        
    - name: Extract version from release tag
      id: version
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
  
    - name: Build AppImage
      run: appimage-builder --recipe AppImageBuilder.yaml --skip-test
        
    - name: Upload AppImage to release
      uses: softprops/action-gh-release@v1
      with:
        files: "*.AppImage"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
